# Generated by Django 4.2.6 on 2023-11-01 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birds',
            name='vision_attribute',
            field=models.BooleanField(default=False, verbose_name='Видел'),
        ),
        migrations.AlterField(
            model_name='birds',
            name='color_feather',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цвет крыльев'),
        ),
        migrations.CreateModel(
            name='View_Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bird', models.ImageField(blank=True, null=True, upload_to='image')),
                ('number_of_views', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('time_date_now', models.DateTimeField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.birds', verbose_name='Название птицы')),
            ],
            options={
                'verbose_name': 'Видел Птицу ',
                'verbose_name_plural': 'Видел Птиц',
            },
        ),
    ]
