# Generated by Django 4.2.6 on 2023-11-01 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_birds_vision_attribute_alter_birds_color_feather_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View_Birds',
            new_name='ViewBirds',
        ),
    ]
